name: Setup deploy environment

runs:
    using: "composite"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.10
            
      - name: Install requirements
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy/requirements.txt

      - name: Create default AWS settings
        shell: bash
        run: |
          mkdir ~/.aws/
          echo -e '[default]\nregion = '$AWS_DEFAULT_REGION > ~/.aws/config

